name: Infinitum
version: '${project.version}'
main: xyz.sakubami.infinitum.Infinitum
api-version: 1.20
author: sakubami
description: Cool Plugin lol
website: sakubami.xyz
softdepend:
  - InteractiveBooks

commands:
  infinitum:
    description: gives the player a note with help
